### ISSUE TITLE
Missing startip and endip attributes from Network struct

### ISSUE THREAD

**Issue by romerojunior** [xanzy/go-cloudstack#103]
Not a Golang developer here, but it seems I can't access the startip and endip attributes from the struct Network when using:
```
cs := meta.(*cloudstack.CloudStackClient)
n, count, err := cs.Network.GetNetworkByID(
	d.Id(),
	cloudstack.WithProject(d.Get("project").(string)),
)
```

Is there any alternative to access? Looking at the NetworkService.go it doesn't seem so.

**Comment by romerojunior** [comment]
This issue comes from the following context:

I'm testing the Terraform `import` feature, for the `cloudstack_network` resource I've tried using the `ImportStatePassthrough` as you've probably seen [here](https://github.com/terraform-providers/terraform-provider-cloudstack/pull/42/commits/b721ce47fe9c0d84440af16441b3f74701e2da4c). 

The import happens, but the attributes `startip` and `endip` (when present on Cloudstack, since they're optional) are missing.

I didn't dig deeper (first time digging into anything written in Go), but seeing the differences between the [read and create](https://github.com/terraform-providers/terraform-provider-cloudstack/blob/b721ce47fe9c0d84440af16441b3f74701e2da4c/cloudstack/resource_cloudstack_network.go#L167-L175) methods, I noticed that the `resourceCloudStackNetworkCreate` set these attributes, but they're not made available when `resourceCloudStackNetworkRead` is called, which are indeed missing from this [struct](https://github.com/xanzy/go-cloudstack/blob/bd1fab829b7ac5541b36b2121c150f42dd2e973a/cloudstack/NetworkService.go#L2606-L2682), which makes it impossible for me to simply return them within [here](https://github.com/terraform-providers/terraform-provider-cloudstack/blob/b721ce47fe9c0d84440af16441b3f74701e2da4c/cloudstack/resource_cloudstack_network.go#L239-L244). 

Maybe (very likely) I'm completely wrong about this approach... if this is the case, could you point me to the correct direction?

**Comment by svanharmelen** [comment]
As there isn't much I can do about this issue in this package, I am going to close this issue for now. Thanks!
