### ISSUE TITLE
LimitService mistake:

### ISSUE THREAD

**Issue by savelyev-an** [xanzy/go-cloudstack#111]
Structure UpdateResourceLimitResponse wait Ressponse from CloudStack in form of:
{"account":"account","domainid":"xxx-xxx--xxx-x-","domain":"ROOT","resourcetype":"0","resourcetypename":"user_vm","max":99}

Actual version of Cloudstack return:

{"resourcelimit":{...UpdateResourceLimitResponse...}}
So, I make request, but got nothing with 200 OK

**Comment by svanharmelen** [comment]
I'm sure I fully understand your issue, but maybe it's good to start by checking which version of CloudStack you are using?

**Comment by savelyev-an** [comment]
We use 
4.11 CloudStack

**Comment by svanharmelen** [comment]
Ok, that should not be the problem then. So can you give some more context about what is happening and what API's you are trying to use?

**Comment by svanharmelen** [comment]
Closing this since no updates were made to my last response.
