### ISSUE TITLE
Guest ostypeid considered as int64 instead of string

### ISSUE THREAD

**Issue by rhtyd** [xanzy/go-cloudstack#117]
This is used as dependency for packer, and the following issue was hit while using packer:
```
cloudstack: Error creating new instance packer-5d0367bd-d45c-0760-b976-6f9a7358c9d0: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64
```

The issue finds its root in recent changes where the guest os type ID was correclty changed from integer to string (so we export UUID and not internal cloudstack ids). Moving the usage throughout `go-cloudstack` may be acceptable:

Issue reference:
https://github.com/apache/cloudstack/issues/2528

Commit reference:
https://github.com/apache/cloudstack/commit/44bc51660917251a1d05e9dbf8124839e6ea00d3

**Comment by rhtyd** [comment]
cc @svanharmelen @PaulAngus @andrijapanic @DaanHoogland @shwstppr @anuragaw

**Comment by svanharmelen** [comment]
Not sure why you opened this issue here? I already updated and fixed this in this code base [1] and a PR to update this in Packer is also merged [2], but not yet released in a new version.

1. https://github.com/xanzy/go-cloudstack/pull/113
2. https://github.com/hashicorp/packer/pull/7694

**Comment by rhtyd** [comment]
@svanharmelen - I'm not aware of the issues you've already fixed, this came from a support issue. I'll close the issue on your remark. Thanks.

**Comment by svanharmelen** [comment]
Al good, thanks!
