### ISSUE TITLE
Module version violates semantic versioning spec

### ISSUE THREAD

**Issue by onitake** [xanzy/go-cloudstack#125]
Since Go modules have become the de facto standard for ensuring dependency compatibility, it is vital that Go packages can be used in the most hassle-free way possible.

go-cloudstack has received numerous releases (thanks to that!), but the current major version number causes problems with the way go-mod treats module versions: https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

In short, module major version numbers should reflect the API compatibility of a module. go-mod allows v0 and v1 to work without specifying a compatibility version, but with a major version >=2, it is required to also version the API. What this means is that a module's packages need to be put into into versioned subpackages, such as: github.com/xanzy/go-cloudstack/v2

Otherwise, Go 1.13 will throw an error of the sort:
> go.mod:7: require github.com/xanzy/go-cloudstack: version "v2.7.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

It is possible to put the dependency into non-semantic mode by specifying the version as v2.7.0+incompatible, but this causes other problems and makes it impossible to import two incompatible module versions side-by-side.

Please consider moving the cloudstack package into cloudstack/v2 to avoid this issue.

**Comment by onitake** [comment]
Sorry, I just noticed that you already fixed this and I still needed to update my import paths.
Thanks!

**Comment by onitake** [comment]
Reopening, because I now get the following error:
> github.com/apache/cloudstack-kubernetes-provider imports
        github.com/xanzy/go-cloudstack/v2: module github.com/xanzy/go-cloudstack/v2@latest found (v2.8.0), but does not contain package github.com/xanzy/go-cloudstack/v2

My go.mod contains this:
```
require (
	github.com/xanzy/go-cloudstack/v2 v2.8.0
)
```
And I'm importing this:
```
import "github.com/xanzy/go-cloudstack/v2"
```

Please advise what the correct package and import path should be so it works without overriding go-mod behaviour.
Thanks!

**Comment by onitake** [comment]
I finally understood how Go interprets these versioning suffixes.
Fixed the problem by changing the import path to:
```
import "github.com/xanzy/go-cloudstack/v2/cloudstack"
```
It works now.
Sorry for bothering you!

**Comment by svanharmelen** [comment]
Yeah, it's not straight forward but it should indeed work with the import you are using now 👍
