### ISSUE TITLE
listVirtualMachines can't work for CloudStack client of latest vertion

### ISSUE THREAD

**Issue by kuku945** [xanzy/go-cloudstack#131]
VirtualMachine.Ostypeid of the response of the ver 4.13 is a string, the json can't unmarshal into int64.

**Comment by olivierlemasle** [comment]
This has already been fixed (cf #113, #117). Please use github.com/xanzy/go-cloudstack/v2 (v2 import)

**Comment by rhugga** [comment]
What is the correct module path or what am I doing wrong here?

```
go: finding module for package github.com/xanzy/go-cloudstack/v2
github.pie.apple.com/isd-dev/monsoon-storage-reporting imports
	github.com/xanzy/go-cloudstack/v2: module github.com/xanzy/go-cloudstack/v2@latest found (v2.9.0), but does not contain package github.com/xanzy/go-cloudstack/v2
```

**Comment by olivierlemasle** [comment]
In` go.mod`, you must use `github.com/xanzy/go-cloudstack/v2`, but in your Go code, you have to use the path `github.com/xanzy/go-cloudstack/v2/cloudstack` (Go code is in the `cloudstack` subdirectory)

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this package has been moved to the Apache Foundation. Please find the new home for this package here: https://github.com/apache/cloudstack-go
