### ISSUE TITLE
getRouterHealthCheckResult api is missing

### ISSUE THREAD

**Issue by ravening** [xanzy/go-cloudstack#132]
The api https://cloudstack.apache.org/api/apidocs-4.14/apis/getRouterHealthCheckResults.html is present in 4.14 but it is missing in this repo

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this package has been moved to the Apache Foundation. Please find the new home for this package here: https://github.com/apache/cloudstack-go

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this package has been moved to the Apache Foundation. Please find the new home for this package here: https://github.com/apache/cloudstack-go
