### ISSUE TITLE
ResourcetagsService dont have projectid field for Create, Delete or List operations

### ISSUE THREAD

**Issue by jairov4** [xanzy/go-cloudstack#135]
We can not specify ProjectID for those operations which block any way to handle tags in resources holded under projects
Affected structs:

- CreateTagsParams
- DeleteTagsParams
- ListTagsParams

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-go
