### ISSUE TITLE
go build of cloudstack fails - killed by signal

### ISSUE THREAD

**Issue by joekhoobyar** [xanzy/go-cloudstack#30]
```
go build github.com/xanzy/go-cloudstack/cloudstack: /usr/lib/go/pkg/tool/linux_amd64/6g: signal: killed
```

It is worth noting that this prevents Terraform from building:  https://github.com/hashicorp/terraform/issues/2426

**Comment by joekhoobyar** [comment]
This is failing using the official 1.4.2 Go distribution - linux amd64

**Comment by joekhoobyar** [comment]
I believe the reason the process gets killed is that the virtual box building this is running out of memory.  Trying again with 2 gigs.

**Comment by joekhoobyar** [comment]
FYI - this is just failing on linux.amd64

**Comment by svanharmelen** [comment]
So lets forget about Terraform for a second. What happens if you do just these commands:

```go
go get -u github.com/xanzy/go-cloudstack/cloudstack
go build github.com/xanzy/go-cloudstack/cloudstack
```

**Comment by joekhoobyar** [comment]
Tried that and it failed, on linux.amd64.  Not on darwin.amd64

**Comment by svanharmelen** [comment]
Yes, but what exactly fails? The first line, or the second? And what is the exact error?

And could you try these instead to get some more output:

```
go get -u -a -v -x github.com/xanzy/go-cloudstack/cloudstack
go build -a -v -x github.com/xanzy/go-cloudstack/cloudstack
```

**Comment by svanharmelen** [comment]
I just did the exact same thing on a linux/amd64 machine (Ubuntu 12.04) and it doesn't give me any issue at all. So I'm having a hard time reproducing this. It feels to me it has to do something with your specific setup so please tell me all there is to know :wink:

You said you are building on VirtualBox, so what is the OS of the guest? And how did you install Go on that machine? Did you compile Go from source? Used the precompiled binaries? Could you post the result of the commands I just gave with the `-a -v -x` parameters? And could you post the output of `go env`?

**Comment by svanharmelen** [comment]
A, just noticed on the other issue at TF you mentioned you tested with both the PPA and Go binaries. Did you uninstall Go first before installing the other one?

Are you on IRC by any chance? I'm just `svanharmelen` on there, would probably be easier. But again, I just tested it myself on Ubuntu x64 I cannot reproduce.

**Comment by joekhoobyar** [comment]
The guest is Ubunty 14.04.2.  It builds if I bump up the RAM to 2 gigs.
