### ISSUE TITLE
Support for additional query params

### ISSUE THREAD

**Issue by hany** [xanzy/go-cloudstack#35]
I'm using a CloudStack provider that requires that additional query parameters be added to all requests, such as:

```
&projectId=<UUID>
```

This query parameter is required on all API calls, and never changes. Does this library currently support this?

**Comment by svanharmelen** [comment]
@hany currently it does not... But it should be relatively easy to add a feature like that I guess.

**Comment by greut** [comment]
@hany [egoscale](https://github.com/exoscale/egoscale) takes a different approach, to the CloudStack API, which lets you do it. `</shamelesspromotion>`

**Comment by svanharmelen** [comment]
@greut they do, but I believe their package is specifically tailored for Exoscale right? So it doesn't fully support standard CloudStack installations...

@hany are there any other standard params that you would like to be able to always pass to the API calls that support them? As I have a pretty straight forward solution for this which I will commit later today. It will allow you to set any [OptionFunc](https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/cloudstack.go#L48) as a default function that should be used by all API calls.

Currently there are two of these functions: [WithProject](https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/cloudstack.go#L394) and [WithVPCID](https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/cloudstack.go#L394). So let me know if you need more/others so I can add them.

**Comment by greut** [comment]
@svanharmelen it aims at being as agnostic as possible. The list of supported API calls is [not complete yet though](https://github.com/exoscale/egoscale/wiki).

**Comment by hany** [comment]
@svanharmelen those would be the only parameters that matter for us in this case. Haven't come across other parameters that are required.

**Comment by svanharmelen** [comment]
@hany see PR #85 I will merge it later today when I have the other fix in as well, after which I will also give the package a new tag...
