### ISSUE TITLE
few examples perhaps?

### ISSUE THREAD

**Issue by serverchief** [xanzy/go-cloudstack#57]
few examples perhaps?

**Comment by svanharmelen** [comment]
I think currently the best location to find examples (quite extensive ones actually) is by having a look at the Terraform CloudStack provider: https://github.com/hashicorp/terraform/tree/master/builtin/providers/cloudstack

This one is build using the `go-cloudstack` package and uses quite a lot of it features. Will look at adding some simple examples (somewhere in the near future) in this repo as well.

**Comment by svanharmelen** [comment]
I just added a basic example in PR #74
