### ISSUE TITLE
securitygroupid and securitygroupname should not be mutually exclusive

### ISSUE THREAD

**Issue by mcanevet** [xanzy/go-cloudstack#64]
`securitygroupname` should be mutually exclusive with `cidr` not `securitygroupid` as it is used to defined the source of an ingress rule or the destination of an egress rule (instead of a `cidr`), not the association between the rule and its security group.

**Comment by svanharmelen** [comment]
@mcanevet can you give me some more details or an example?

The `go-cloudstack` package tries to follow the behaviour of the CloudStack API as much as possible and is generated based on the output of the `listApis` call.

So is there is something unlogical in the CloudStack API, it will be the same in the `go-cloudstack` package.

**Comment by mcanevet** [comment]
Actually I must be wrong. According to the API (https://cloudstack.apache.org/api/apidocs-4.4/user/authorizeSecurityGroupIngress.html), `securitygroupid` and `securitygroupname` are mutally exclusive. So the field I'm looking for (define the source or destination security group on which the rule applies) is not `authorizeSecurityGroup(E|In)gress`'s `securitygroupname` even if when I call `listSecurityGroups` I see it as `(e|in)gressrule`'s `securitygroupname`. Maybe it's `usersecuritygrouplist` but it's not really clear...

**Comment by svanharmelen** [comment]
@mcanevet check... So in that case we are following the API correctly. That's good to know.

As for your use case, it's still not clear to me what you are trying to achieve. You want to find the security group a rule belong to based on the response you get when making an `authorizeSecurityGroup(E|In)gress` call?

**Comment by mcanevet** [comment]
With cloudstack (and most cloud provider that support SG AFAIK) you can define a SG rule that takes as source (or destination, depending of the direction of your rule) either a CIDR or a SG. For my case, it looks like I have to use `usersecuritygrouplist` but it's a `map[string]string` ([{account: <account>, securitygroupid: <sgid>}, ...]) and I can't figure out (yet) what to put in it.

**Comment by mcanevet** [comment]
I found some information here: https://github.com/exoscale/cs/issues/5
