### ISSUE TITLE
the format of the parameters in the  parameter struct

### ISSUE THREAD

**Issue by zxr445116086** [xanzy/go-cloudstack#75]
Thanks a lot for your support of adding an example!   It's really helpful!

I'm not familiar with Go language, so I still have a question. In this line of code:
p := cs.VirtualMachine.NewDeployVirtualMachineParams("service-offering-id", "template-id", "zone-id")

I just need to replace "service-offering-id", "template-id", "zone-id" with 1234, 324, 32423, like this:
p := cs.VirtualMachine.NewDeployVirtualMachineParams(1234, 324, 32423)

or I should write like this:
p := cs.VirtualMachine.NewDeployVirtualMachineParams(service-offering-id=1234, template-id=324, zone-id=32423)

**Comment by svanharmelen** [comment]
Please do not open a new issue for these kind of questions. If you have user questions you better ask them here: https://gitter.im/xanzy/go-cloudstack

As for this question, you should replace the fields with their respective CloudStack UUID (which are strings):

`p := cs.VirtualMachine.NewDeployVirtualMachineParams("uuid", "uuid", "uuid")`

Please also check out this tour https://tour.golang.org/welcome/1 as it will teach/explain the basics of Go.
