### ISSUE TITLE
Support for custom commands

### ISSUE THREAD

**Issue by andrestc** [xanzy/go-cloudstack#77]
Our cloudstack installation has a couple of custom API endpoints for some custom commands. 
Is there a way to do such calls using this lib?

I think an easy way to support such use case would be to turn [`newRequest`](https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/cloudstack.go#L286) exported. I would happily open a PR for that if its ok.

**Comment by svanharmelen** [comment]
Yeah, that should be possible. But instead of changing `newRequest`, maybe add a function called `CustomRequest` which also accepts options like the other functions do?

This leaves some room to easily tweak things in the future and to support the existing `WithProject` and other options.

**Comment by andrestc** [comment]
Sounds great, I'll open up a PR once I get this done

**Comment by svanharmelen** [comment]
Cool... Thx!
