### ISSUE TITLE
Fix VM details map for Deploy, Update, Change Service VM calls

### ISSUE THREAD

**Issue by mlsorensen** [xanzy/go-cloudstack#84]
deployVirtualMachine and updateVirtualMachine require a format of e.g.:

        details[0].cpuSpeed=500

Currently this is being submitted as:

        details[0].key=cpuSpeed,details[0].value=500

I've experimented with fixing this in generate.go, however I'm not certain I've come up with the best way to make it apply only to the 'details' maps needed in VirtualMachineService or if there are other APIs that might require the same format. 

The basic format is:

`pn("    u.Set(fmt.Sprintf(\"%s[%%d].%%s\", i, k), vv)", name)`

**Comment by svanharmelen** [comment]
Thanks for the report @mlsorensen... Could you point me to some documentation that describes and/or confirms the format you are suggesting?

**Comment by mlsorensen** [comment]
The CloudStack API docs don't really provide much in regards to how the 'details' field works. I'll see if I can dig up examples from other API implementations or source code.

**Comment by mlsorensen** [comment]
You can see here in CloudStack's Marvin smoke testing module that they're using the "details[0].cpuSpeed = value" format:

https://github.com/apache/cloudstack/blob/67f509dc5768a1a7ad2a64dbe2e30c56fe8bd429/tools/marvin/marvin/lib/base.py#L558

**Comment by greut** [comment]
> Template details in key/value pairs using format `details[i].keyname=keyvalue`. Example: `details[0].hypervisortoolsversion=xenserver61`
>
> https://github.com/apache/cloudstack/blob/87ef8137534fa798101f65c6691fcf71513ac978/api/src/org/apache/cloudstack/api/command/user/template/CreateTemplateCmd.java#L123

**Comment by svanharmelen** [comment]
@mlsorensen PR #86 should fix this problem. I'll merge it in a bit and will tag a new release. Let me know if you encounter any additional issues.
