### ISSUE TITLE
Can't set RoleID in NewLdapCreateAccountParams

### ISSUE THREAD

**Issue by somejfn** [xanzy/go-cloudstack#90]
Would be nice to be able to create Ldap based accounts with non-default User roles.  Im testing with ACS 4.9.3.   Also, there are no method to create or list for Roles in general.

**Comment by svanharmelen** [comment]
@somejfn if you can provide me the JSON output of a `listApis` call against that 4.9.3 install (or newer), I can update the code with that... Thx!

**Comment by somejfn** [comment]
Please see attached.
[listApis.txt](https://github.com/xanzy/go-cloudstack/files/1826010/listApis.txt)
