### ISSUE TITLE
OutOfBandManagementResponse type missing

### ISSUE THREAD

**Issue by csquire** [xanzy/go-cloudstack#96]
When calling `HostService.ListHosts`, the response cannot be deserialzed.  The problem is that the ``Outofbandmanagement  string `json:"outofbandmanagement"` `` field in the `Host` struct needs to be OutOfBandManagementResponse type, but is defaulting to string. The same problem will likely occur in other API responses which require the same type.

`Error getting host list: json: cannot unmarshal object into Go struct field Host.outofbandmanagement of type string`

The format returned from listHosts is:
`      "outofbandmanagement": {
        "powerstate": "Disabled",
        "enabled": false
      },`

I tried to understand how the code generator works in this case, but was unable to figure out the correct way to fix this issue to submit a PR.

**Comment by svanharmelen** [comment]
Should be fixed in master now :wink:

**Comment by csquire** [comment]
Fantastic, thanks!
